server:
#  port: 8080
  port: 8443
  ssl:
    enabled: true
#    key-store: /opt/tomcat/Wildcard.ubcare.co.kr_iis.jks
#    key-store: D:\01_vodacom\01_Project\01_IMS\01_SpringBoot\UBcare\boot\ims_ubcare\src\main\resources\Wildcard.ubcare.co.kr_iis.jks
    key-store: C:\Users\82106\IdeaProjects\실무\ims_ubcare\ims_ubcare\src\main\resources\Wildcard.ubcare.co.kr_iis.jks
    key-store-type: PKCS12 #인증서 파일 포맷별 "JKS" 또는 "PKCS12" 지정
    key-store-password: ubcare5232  # jks 또는 pfx 암호
  servlet:
    context-path: /ims
  error:
    path: /error

---

#
#spring:
#  main:
#    allow-bean-definition-overriding: true

---

# database 설정
spring:
  datasource:
    hikari: #main
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      jdbc-url: jdbc:log4jdbc:mysql://192.168.120.188:3306/ims?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/ims?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
#      username: vdc
#      password: vdc7200#
      username: root
      password: 7200
      #connection-test-query: SELECT NOW()
      max-lifetime: 580000 #580s
#      hikari2: #sub:
#        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#        jdbc-url: jdbc:log4jdbc:sqlserver://localhost:1433;DatabaseName=IMS
#        username: vdc
#        password: vdc7200#
#        max-lifetime: 580000 #580s
#        connection-test-query: select getdate() as MSSQL
    hikari2: #sub:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:sqlserver://192.168.102.49:1433;DatabaseName=IMS
      username: vdc
      password: vdc7200#
      max-lifetime: 580000 #580s
      connection-test-query: select getdate() as MSSQL
#    hikari2: #sub:
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      jdbc-url: jdbc:log4jdbc:sqlserver://192.168.120.12:3077;DatabaseName=VodaComCTI #실서버
#      username: CTIApplicationsa
#      password: CT!doq11roqkf##
#      max-lifetime: 580000 #580s
#      connection-test-query: select getdate() as MSSQL

---
# devtools
spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

---
#thymeleaf 사용
spring:
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false

---
#tts설정
tts:
  server: 192.168.120.211
  port: 7000
  speakerid: 14 #TTS_HYERYUN_DB
  voiceformat: 12 #8bit A-law PCM Wave
  volume: 100
  speed: 100
  pitch: 100 #합성음 높낮이
  temppath: /tmp/ #로컬 임시 저장 path

---

#IVR SFTP
ftp:
  servermain: 192.168.120.206
  serversub: 192.168.120.207
  port: 22
  userid: ubadmin
  password: Ubcare@cti1504~
  target: /usr/share/freeswitch/sounds

#로그 레벨
logging:
  config:
    level: INFO
    path: /opt/tomcat/latest/logs #/logs
    filename: ims
    errfilename: ims_error

---

#MultipartUpload
spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
upload:
  temppath: C:\Temp\
  boardpath: /upload/board/
  minibarpath: /upload/minibar/

